apiVersion: apps/v1
kind: Deployment
metadata:
  name: determined-master-deployment-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: determined-master-{{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: determined-master-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: determined-master-{{ .Release.Name }}
      annotations:
        # This is added so that the master deployment restarts when an upgrade occurs that
        # changes the master-config.yaml.
        checksum/config: {{ include (print $.Template.BasePath "/master-config.yaml") . | sha256sum }}
    spec:
      serviceAccount: determined-master-{{ .Release.Name }}
      containers:
      - name: determined-master-{{ .Release.Name }}
        {{ $image := "determinedai/determined-master" }}
        {{- if .Values.enterpriseEdition -}}
          {{ $image = "determinedai/determined-ee-master" }}
        {{- end -}}
        {{ $tag := (required "A valid Chart.AppVersion entry required!" .Chart.AppVersion) }}
        {{- if .Values.detVersion -}}
          {{ $tag =  .Values.detVersion }}
        {{- end -}}
        image: {{ $image }}:{{ $tag }}
        imagePullPolicy: "Always"
        volumeMounts:
          - name: master-config
            mountPath: /etc/determined/
            readOnly: true
          {{- if .Values.tlsSecret }}
          - name: tls-secret
            mountPath: {{ include "determined.secretPath" . }}
            readOnly: true
          {{ end }}
        resources:
          requests:
            {{- if .Values.masterCpuRequest }}
            cpu: {{ .Values.masterCpuRequest  | quote }}
            {{- end }}
            {{- if .Values.masterMemRequest }}
            memory: {{ .Values.masterMemRequest  | quote }}
            {{- end}}
      {{- if .Values.enterpriseEdition }}
      imagePullSecrets:
      - name: {{ required "A valid Values.imagePullSecretName entry is required!" .Values.imagePullSecretName | quote}}
      {{- end }}
      volumes:
        - name: master-config
          configMap:
            name: determined-master-config-{{ .Release.Name }}
        {{- if .Values.tlsSecret }}
        - name: tls-secret
          secret:
            secretName: {{ .Values.tlsSecret }}
        {{ end }}
