apiVersion: v1
kind: Service
metadata:
  name: determined-master-service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: determined-master-{{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ required "A valid Values.masterPort entry required!" .Values.masterPort }}
    protocol: TCP
  {{ $serviceType := "LoadBalancer" }}
  {{- if .Values.useNodePortForMaster | default false -}}
    {{ $serviceType = "NodePort" }}
  {{- end }}
  type: {{ $serviceType }}
  selector:
    app: determined-master-{{ .Release.Name }}
