# httpPort controls the port at which the listens for connections on.
httpPort: 8080 

# db sets the configurations for the database.
db:
  name: determined
  user: postgres
  password: postgres
  port: 5432

# checkpointStorage controls where checkpoints are stored.
# supported types include `shared_fs`, `gcs`, and `s3.
checkpointStorage:
  # comment out if not using `shared_fs`
  type: shared_fs
  hostPath: /checkpoints

  # For storing in gcs.
  # type: gcs
  # bucket: <bucket_name>

  # For storing in s3.
  # type: s3
  # bucket: <bucket_name>
  # accessKey: <access_key>
  # secretKey: <secret_key>
  # endpointUrl: <endpoint_url>
